<?php
/**
 * TL_ROOT/system/modules/myfavicon/languages/cs/tl_page.php 
 * 
 * Contao extension: myfavicon 0.1.1 stable 
 * Czech translation file 
 * 
 * Copyright : Copyright &copy; 2010-2012 Thyon Design 
 * License   : LGPL 
 * Author    : Thyon Design (thyon), http://www.thyon.com/ 
 * Translator: Tomas Petrlik (frogzone), www.frogzone.cz 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['addFavicon']['0'] = "Přidat favicon";
$GLOBALS['TL_LANG']['tl_page']['addFavicon']['1'] = "Umožňuje přidat favicon, které budou vytvořena z PNG, JPG nebo GIF, nebo nastavit od ICO.";
$GLOBALS['TL_LANG']['tl_page']['favicon']['0'] = "Favicon soubor";
$GLOBALS['TL_LANG']['tl_page']['favicon']['1'] = "Prosím vyberte favicon soubor pro tuto doménu. ICO jako je PNG a GIF převést dynamicky na ICO.";
$GLOBALS['TL_LANG']['tl_page']['rootFavicon']['0'] = "Připojit kořenový alias k souboru";
$GLOBALS['TL_LANG']['tl_page']['rootFavicon']['1'] = "Přidá aktuální kořen Alias ​​favicon souboru před propojením, např. <em>favicon-myroot.ico</em>.";
$GLOBALS['TL_LANG']['tl_page']['fbFavicon']['0'] = "Přidat jako výchozí obraz Facebook";
$GLOBALS['TL_LANG']['tl_page']['fbFavicon']['1'] = "Přidá favicon jako výchozí obrázek webu pro Facebook (doporučeno).";
$GLOBALS['TL_LANG']['tl_page']['favicon_legend'] = "Favicon nastavení";
 
?>
