<?php
/**
 * TL_ROOT/system/modules/myfavicon/languages/ja/tl_page.php 
 * 
 * Contao extension: myfavicon 0.1.1 stable 
 * Japanese translation file 
 * 
 * Copyright : Copyright &copy; 2010-2012 Thyon Design 
 * License   : LGPL 
 * Author    : Thyon Design (thyon), http://www.thyon.com/ 
 * Translator: Takahiro Kambe (taca), http://www.contaocms.jp/ 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['addFavicon']['0'] = "faviconを追加";
$GLOBALS['TL_LANG']['tl_page']['addFavicon']['1'] = "faviconを指定したPNGやGIFファイルから作成、またはICOファイルを指定します。";
$GLOBALS['TL_LANG']['tl_page']['favicon']['0'] = "Faviconのファイル";
$GLOBALS['TL_LANG']['tl_page']['favicon']['1'] = "このドメイン用のfaviconのファイルを選択してください。ICOファイルはそのまま使用し、PNGとGIFは動的にICOファイルに変換します。";
$GLOBALS['TL_LANG']['tl_page']['rootFavicon']['0'] = "ルートのエイリアスをファイル名に追加";
$GLOBALS['TL_LANG']['tl_page']['rootFavicon']['1'] = "ウェブサイトのルートのページのエイリアスを、リンクを作成する前にfaviconファイルの名前に加えます。例: <em>favicon-myroot.ico</em>";
$GLOBALS['TL_LANG']['tl_page']['fbFavicon']['0'] = "Facebookのデフォルトの画像として追加";
$GLOBALS['TL_LANG']['tl_page']['fbFavicon']['1'] = "faviconをFacebookのデフォルトの画像として追加します。(推奨)";
$GLOBALS['TL_LANG']['tl_page']['favicon_legend'] = "Faviconの設定";
 
?>
