<?php
/**
 * TL_ROOT/system/modules/myfavicon/languages/de/tl_page.php 
 * 
 * Contao extension: myfavicon 0.1.0 stable 
 * German translation file 
 * 
 * Copyright : Copyright &copy; 2010 Thyon Design 
 * License   : LGPL 
 * Author    : John Brand (thyon), http://www.thyon.com/ 
 * Translator: Sebastian Leitz (Sebastian) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_page']['addFavicon']['0'] = "Favicon hinzufügen";
$GLOBALS['TL_LANG']['tl_page']['addFavicon']['1'] = "Diese Option aktiviert die Erstellung eines Favicons aus einer Grafik.";
$GLOBALS['TL_LANG']['tl_page']['favicon']['0'] = "Ursprungsdatei";
$GLOBALS['TL_LANG']['tl_page']['favicon']['1'] = "Bitte wählen Sie eine Ursprungsdateien. ICO-Dateien werden direkt übernommen, PNG und GIF werden ins ICO-Format konvertiert.";
$GLOBALS['TL_LANG']['tl_page']['rootFavicon']['0'] = "Alias des Startpunktes zum Dateinamen hinzufügen";
$GLOBALS['TL_LANG']['tl_page']['rootFavicon']['1'] = "Diese Option ändert den Dateinamen des Favicons für Multidomaininstallationen (z.B. <em>favicon-myroot.ico</em>).";
$GLOBALS['TL_LANG']['tl_page']['favicon_legend'] = "Favicon-Einstellungen";
 
?>
